-- --------------------------------------------------------
-- Hôte :                        127.0.0.1
-- Version du serveur:           8.0.18 - MySQL Community Server - GPL
-- SE du serveur:                Win64
-- HeidiSQL Version:             10.3.0.5771
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Listage de la structure de la base pour db_purebeurre
CREATE DATABASE IF NOT EXISTS `db_purebeurre` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `db_purebeurre`;

-- Listage de la structure de la table db_purebeurre. aliment
CREATE TABLE IF NOT EXISTS `aliment` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `product_name` varchar(100) NOT NULL,
  `local_name` varchar(100) NOT NULL DEFAULT 'NO_INFO',
  `local_category` varchar(50) NOT NULL,
  `brands` varchar(100) NOT NULL,
  `nutriscore_grade` varchar(100) NOT NULL,
  `stores` varchar(100) NOT NULL DEFAULT 'NO_INFO',
  `purchase_places` varchar(100) NOT NULL DEFAULT 'NO_INFO',
  `url` longtext NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_sub_category` (`local_category`),
  CONSTRAINT `FK_sub_category` FOREIGN KEY (`local_category`) REFERENCES `category` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=01 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Listage des données de la table db_purebeurre.aliment : ~0 rows (environ)
/*!40000 ALTER TABLE `aliment` DISABLE KEYS */;
INSERT INTO `aliment` (`id`, `product_name`, `local_name`, `local_category`, `brands`, `nutriscore_grade`, `stores`, `purchase_places`, `url`) VALUES
	(1, 'Balade So light', 'beurre_0', 'beurre', ' Balade', ' d', ' Delhaize', ' ', ' https://fr.openfoodfacts.org/produit/5411156002384/balade-so-light'),
	(2, 'Aceite de oliva suave 0 ou 4º', 'huile_0', 'huile', ' Carbonell', ' c', ' ', ' ', ' https://fr.openfoodfacts.org/produit/8410010009689/aceite-de-oliva-suave-0-4-carbonell'),
	(3, 'Tomato ketchup', 'ketchup_0', 'ketchup', ' Heinz', ' d', ' Magasins U', ' France ou Suisse', ' https://fr.openfoodfacts.org/produit/87157215/tomato-ketchup-heinz'),
	(4, 'Maionese portugaise', 'mayonnaise_0', 'mayonnaise', ' Rustica', ' e', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/5606456010997/maionese-portugaise-rustica'),
	(5, 'Classic Yellow mustard', 'moutarde_0', 'moutarde', ' French-s', ' c', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/0056200762163/classic-yellow-mustard-french-s'),
	(6, 'Ristorante pizza quattro formaggi', 'pizza_0', 'pizza', ' Dr.Oetker', ' d', ' Dia ou Woolworths ou Coles ou Intermarché ou Magasins U', ' Villecresnes ou France ou Blois', ' https://fr.openfoodfacts.org/produit/4001724818908/ristorante-pizza-quattro-formaggi-dr-oetker'),
	(7, 'Quiche Lorraine sans pate', 'quiche_0', 'quiche', ' Weight Watchers', ' b', ' Carrefour ou Casino', ' Flers-en-Escrebieux ou France ou Paris ou Maison-Laffitte', ' https://fr.openfoodfacts.org/produit/3248832940584/quiche-lorraine-sans-pate-weight-watchers'),
	(8, 'Arroz basmati aromático del Himalaya', 'riz_0', 'riz', ' El Corte Inglés', ' b', ' ', ' ', ' https://fr.openfoodfacts.org/produit/8433329018821/arroz-basmati-aromatico-del-himalaya-el-corte-ingles'),
	(9, 'Fuet extra', 'saucisse_0', 'saucisse', ' El Corte Ingles', ' e', ' ', ' ', ' https://fr.openfoodfacts.org/produit/8433329025485/fuet-extra-el-corte-ingles'),
	(10, 'Steaks haches pur boeuf 10% Mg', 'steack_0', 'steack', ' Toupargel', ' b', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3273230252175/steaks-haches-pur-boeuf-10-mg-toupargel'),
	(11, 'NOT_PROVIDED', 'beurre_1', 'beurre', ' St Hubert', ' c', ' ', ' ', ' https://fr.openfoodfacts.org/produit/3366321053246/omega-3-st-hubert'),
	(12, 'Cremefine', 'huile_1', 'huile', ' NOT_PROVIDED', ' NOT_PROVIDED', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/8719200040595/cremefine'),
	(13, 'French-s Ketchup', 'ketchup_1', 'ketchup', ' French-s', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/0056200951215/french-s-ketchup'),
	(14, 'Mayonnaise à la moutarde à l-Ancienne', 'mayonnaise_1', 'mayonnaise', ' Rustica ou Marque Repère', ' d', ' Leclerc', ' ', ' https://fr.openfoodfacts.org/produit/3564700643990/mayonnaise-a-la-moutarde-a-l-ancienne-rustica'),
	(15, 'Classic Yellow Prepared Mustard - Sweet', 'moutarde_1', 'moutarde', ' French-s', ' c', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/0056200933037/classic-yellow-prepared-mustard-sweet-french-s'),
	(16, 'Ristorante pizza prosciutto', 'pizza_1', 'pizza', ' Dr.Oetker', ' c', ' Willys ou Coop Konsum', ' Sweden', ' https://fr.openfoodfacts.org/produit/4001724819202/ristorante-pizza-prosciutto-dr-oetker'),
	(17, 'Quiche Lorraine Surgelée', 'quiche_1', 'quiche', ' Carrefour', ' b', ' Carrefour', ' France ou Nantes', ' https://fr.openfoodfacts.org/produit/3270190216063/quiche-lorraine-surgelee-carrefour'),
	(18, 'Riz Basmati Bio', 'riz_1', 'riz', ' Auchan Bio ou Auchan', ' a', ' ', ' ', ' https://fr.openfoodfacts.org/produit/3596710477326/riz-basmati-bio-auchan-bio'),
	(19, 'Saucisses Cocktail rondes', 'saucisse_1', 'saucisse', ' Carrefour', ' d', ' Carrefour', ' Flers-en-Escrebieux ou France', ' https://fr.openfoodfacts.org/produit/3245412966156/saucisses-cocktail-rondes-carrefour'),
	(20, 'Steaks Hachés Pur Boeuf', 'steack_1', 'steack', ' Toupargel', ' b', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3265980786086/steaks-haches-pur-boeuf-toupargel'),
	(21, 'Beurre demi-sel', 'beurre_2', 'beurre', ' Isigny Ste Mère', ' e', ' Delhaize', ' ', ' https://fr.openfoodfacts.org/produit/3254550022358/beurre-demi-sel-isigny-ste-mere'),
	(22, 'Huile d-avocat', 'huile_2', 'huile', ' Chosen Foods', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/0853807005163/huile-d-avocat-chosen-foods'),
	(23, 'ketchup', 'ketchup_2', 'ketchup', ' Bionaturae', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/13633653/ketchup-bionaturae'),
	(24, 'Amora Mayonnaise Dijon Nature Œufs Français Flacon Souple 225g', 'mayonnaise_2', 'mayonnaise', ' Amora', ' e', ' Intermarché', ' France', ' https://fr.openfoodfacts.org/produit/8714100867006/amora-mayonnaise-dijon-nature-oeufs-francais-flacon-souple-225g'),
	(25, 'Moutarde', 'moutarde_2', 'moutarde', ' French-s', ' NOT_PROVIDED', ' ', ' ', ' https://fr.openfoodfacts.org/produit/0056200762170/moutarde-french-s'),
	(26, 'Goat cheese pizza', 'pizza_2', 'pizza', ' Alasature', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/8437016108390/goat-cheese-pizza-alasature'),
	(27, 'Quiche lorraine aux oeufs frais', 'quiche_2', 'quiche', ' Côté Table ou Marque Repère', ' c', ' Leclerc', ' France ou Drumettaz Clarafond', ' https://fr.openfoodfacts.org/produit/3564700006368/quiche-lorraine-aux-oeufs-frais-cote-table'),
	(28, 'Le basmati Pur HIMALAYA', 'riz_2', 'riz', ' Taureau ailé', ' a', ' ', ' ', ' https://fr.openfoodfacts.org/produit/3038354592305/le-basmati-pur-himalaya-taureau-aile'),
	(29, 'Wiener Würstchen', 'saucisse_2', 'saucisse', ' viel Leicht', ' NOT_PROVIDED', ' ', ' ', ' https://fr.openfoodfacts.org/produit/4314240074575/wiener-wurstchen-viel-leicht'),
	(30, '10 steaks hachés pur boeuf 15% matières grasses', 'steack_2', 'steack', ' Toupargel', ' c', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3265980786062/10-steaks-haches-pur-boeuf-15-matieres-grasses-toupargel'),
	(31, 'Beurre', 'beurre_3', 'beurre', ' Montfleuri', ' d', ' Carrefour Market ou Magasins U', ' Villecresnes', ' https://fr.openfoodfacts.org/produit/3451790563256/beurre-montfleuri'),
	(32, 'Olivenöl', 'huile_3', 'huile', ' Lyttos', ' NOT_PROVIDED', ' ', ' ', ' https://fr.openfoodfacts.org/produit/5202423202541/olivenol-lyttos'),
	(33, 'Heinz Curry Ketchup Squeeze 400 ML', 'ketchup_3', 'ketchup', ' Heinz', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/87157413/heinz-curry-ketchup-squeeze-400-ml'),
	(34, 'Amora Bio Mayonnaise Standard Flacon Souple 280g', 'mayonnaise_3', 'mayonnaise', ' Amora', ' e', ' ', ' ', ' https://fr.openfoodfacts.org/produit/8711200473045/amora-bio-mayonnaise-standard-flacon-souple-280g'),
	(35, 'Dijon Mustard Originale', 'moutarde_3', 'moutarde', ' Maille ou Unilever', ' d', ' ', ' San Francisco ou California ou USA', ' https://fr.openfoodfacts.org/produit/0043646201288/dijon-mustard-originale-maille'),
	(36, '3 Pizzas Individuelles Reine', 'pizza_3', 'pizza', ' Toupargel', ' c', ' ', ' ', ' https://fr.openfoodfacts.org/produit/4002084333063/3-pizzas-individuelles-reine-toupargel'),
	(37, 'Mini quiche de puerro', 'quiche_3', 'quiche', ' Aldi', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/24054447/mini-quiche-de-puerro-aldi'),
	(38, 'Riz Thaï du Plateau de l-I-San', 'riz_3', 'riz', ' Taureau ailé', ' b', ' Magasins U', ' ', ' https://fr.openfoodfacts.org/produit/3038359007231/riz-thai-du-plateau-de-l-i-san-taureau-aile'),
	(39, 'Cheesy snack-s', 'saucisse_3', 'saucisse', ' Isla mondial', ' a', ' NOT_PROVIDED', ' France', ' https://fr.openfoodfacts.org/produit/3459860005156/cheesy-snack-s-isla-mondial'),
	(40, 'Steak haché', 'steack_3', 'steack', ' Leader Price', ' NOT_PROVIDED', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3265980127179/steak-hache-leader-price'),
	(41, 'Beurre Extra-Fin Doux (82 % MG)', 'beurre_4', 'beurre', ' Grand Fermage ou Eurial', ' e', ' Casino ou Carrefour market ou Magasins U ou Carrefour', ' Clichy ou Villers Bocage 80260', ' https://fr.openfoodfacts.org/produit/3354599571005/beurre-extra-fin-doux-82-mg-grand-fermage'),
	(42, 'Huile D-amande Vierge Bio - 250 ML - La Mandorle', 'huile_4', 'huile', ' La Mandorle', ' NOT_PROVIDED', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3760030728110/huile-d-amande-vierge-bio-250-ml-la-mandorle'),
	(43, 'Amora Petit Ketchupier Souple 280g', 'ketchup_4', 'ketchup', ' Amora ou Unilever', ' d', ' Magasins U', ' France', ' https://fr.openfoodfacts.org/produit/8722700113348/amora-petit-ketchupier-souple-280g'),
	(44, 'Mayonnaise à la moutarde de Dijon', 'mayonnaise_4', 'mayonnaise', ' Vitad-or', ' e', ' Lidl', ' France ou Gap ou 05000', ' https://fr.openfoodfacts.org/produit/20183363/mayonnaise-a-la-moutarde-de-dijon-vitad-or'),
	(45, 'Moutarde d-Orléans Tomate', 'moutarde_4', 'moutarde', ' Martin Pouret', ' d', ' Magasins U', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3165355920803/moutarde-d-orleans-tomate-martin-pouret'),
	(46, 'Pizza au thon', 'pizza_4', 'pizza', ' Toupargel', ' c', ' ', ' ', ' https://fr.openfoodfacts.org/produit/4002084341198/pizza-au-thon-toupargel'),
	(47, 'Tarte aux poireaux 2 x 130 g', 'quiche_4', 'quiche', ' Côté table ou Marque Repère', ' d', ' Leclerc', ' France', ' https://fr.openfoodfacts.org/produit/3564700427521/tarte-aux-poireaux-2-x-130-g-cote-table'),
	(48, 'Rizblanc', 'riz_4', 'riz', ' Markal', ' a', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3329485431206/rizblanc-markal'),
	(49, 'Diot de Savoie pur porc au beaufort aop', 'saucisse_4', 'saucisse', ' Aux Salaisons Savoyardes', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3538350005361/diot-de-savoie-pur-porc-au-beaufort-aop-aux-salaisons-savoyardes'),
	(50, 'Steak haché de boeuf bio', 'steack_4', 'steack', ' Bio village', ' NOT_PROVIDED', ' Leclerc', ' France', ' https://fr.openfoodfacts.org/produit/3661112090685/steak-hache-de-boeuf-bio-bio-village'),
	(51, 'Beurre d-Ardenne baratté', 'beurre_5', 'beurre', ' Delhaize', ' NOT_PROVIDED', ' Delhaize', ' ', ' https://fr.openfoodfacts.org/produit/5400112104408/beurre-d-ardenne-baratte-delhaize'),
	(52, 'Olio extra vergine di oliva 100 % Italiano', 'huile_5', 'huile', ' Italiamo', ' c', ' LIDL', ' Lyon ou France', ' https://fr.openfoodfacts.org/produit/20032432/olio-extra-vergine-di-oliva-100-italiano-italiamo'),
	(53, 'Ketchup', 'ketchup_5', 'ketchup', ' Tabaluga', ' c', ' ', ' ', ' https://fr.openfoodfacts.org/produit/4311596602124/ketchup-tabaluga'),
	(54, 'Mayonnaise', 'mayonnaise_5', 'mayonnaise', ' Delique', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/4316268391368/mayonnaise-delique'),
	(55, 'Moutarde Rustica', 'moutarde_5', 'moutarde', ' Rustica', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/5606456011000/moutarde-rustica'),
	(56, 'Pizza reine', 'pizza_5', 'pizza', ' Auchan', ' c', ' Magasins U ou Auchan', ' ', ' https://fr.openfoodfacts.org/produit/8712000051174/pizza-reine-auchan'),
	(57, '2 tartes aux poireaux', 'quiche_5', 'quiche', ' Les p-tits chefs du bio ou Les belles gourmandes ou Nutrition santé', ' d', ' Biocoop', ' France ou Versailles', ' https://fr.openfoodfacts.org/produit/3760209680225/2-tartes-aux-poireaux-les-p-tits-chefs-du-bio'),
	(58, 'Riz Basmati', 'riz_5', 'riz', ' Carrefour Bio ou Carrefour', ' a', ' Carrefour', ' France', ' https://fr.openfoodfacts.org/produit/3560070393619/riz-basmati-carrefour-bio'),
	(59, 'Saucisses Cocktail Apéro Nature', 'saucisse_5', 'saucisse', ' Stéphan', ' e', ' ', ' France', ' https://fr.openfoodfacts.org/produit/3261830407934/saucisses-cocktail-apero-nature-stephan'),
	(60, 'Steak haché', 'steack_5', 'steack', ' Carrefour', ' d', ' Carrefour Market ou  Carrefour', ' France ou Miribel', ' https://fr.openfoodfacts.org/produit/3245413841841/steak-hache-carrefour'),
	(61, 'Vitelma Light', 'beurre_6', 'beurre', ' Vitelma', ' c', ' Delhaize', ' ', ' https://fr.openfoodfacts.org/produit/5410093146298/vitelma-light'),
	(62, 'Sonnenblumen-Öl', 'huile_6', 'huile', ' Ja!', ' NOT_PROVIDED', ' ', ' ', ' https://fr.openfoodfacts.org/produit/4388844268128/sonnenblumen-ol-ja'),
	(63, 'Tomato Ketchup', 'ketchup_6', 'ketchup', ' NOT_PROVIDED', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/4316268487795/tomato-ketchup'),
	(64, 'Mayonnaise à la moutarde de Dijon', 'mayonnaise_6', 'mayonnaise', ' Jardin Bio', ' NOT_PROVIDED', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3760020506254/mayonnaise-a-la-moutarde-de-dijon-jardin-bio'),
	(65, 'Amora Moutarde Douce Bocal 435g', 'moutarde_6', 'moutarde', ' Amora', ' d', ' Magasins U', ' France', ' https://fr.openfoodfacts.org/produit/8722700139201/amora-moutarde-douce-bocal-435g'),
	(66, 'Pizza Chevre', 'pizza_6', 'pizza', ' Manosque', ' c', ' Cora', ' France', ' https://fr.openfoodfacts.org/produit/3424600000784/pizza-chevre-manosque'),
	(67, 'TARTES Poireaux & Saumon', 'quiche_6', 'quiche', ' Carte Nature', ' c', ' ', ' ', ' https://fr.openfoodfacts.org/produit/3700477606534/tartes-poireaux-saumon-carte-nature'),
	(68, 'Riz Thaï', 'riz_6', 'riz', ' Carrefour ou Carrefour Bio', ' a', ' Carrefour', ' France', ' https://fr.openfoodfacts.org/produit/3560070393589/riz-thai-carrefour'),
	(69, 'Delikatess Geflügel-Wiener mit Rapsöl', 'saucisse_6', 'saucisse', ' Mühlenhof', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/27038307/geflugelwiener-mit-rapsol-muhlenhof'),
	(70, 'Mon Haché Burger à la tomate', 'steack_6', 'steack', ' NOT_PROVIDED', ' a', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3273230068776/mon-hache-burger-a-la-tomate'),
	(71, 'St Hubert doux - sans huile de palme', 'beurre_7', 'beurre', ' St Hubert', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/3366321054243/st-hubert-doux-sans-huile-de-palme'),
	(72, 'Olio Extra Vergine Di Oliva', 'huile_7', 'huile', ' Bertolli', ' NOT_PROVIDED', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/8002470015487/olio-extra-vergine-di-oliva-bertolli'),
	(73, 'Tomato Ketchup', 'ketchup_7', 'ketchup', ' Heinz', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/8715700421629/tomato-ketchup-heinz'),
	(74, 'Mayonnaise à la moutarde de Dijon', 'mayonnaise_7', 'mayonnaise', ' Jardin Bio', ' e', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3760020675554/mayonnaise-a-la-moutarde-de-dijon-jardin-bio'),
	(75, 'Amora Moutarde Fine et Forte Verre De Table 245g', 'moutarde_7', 'moutarde', ' Amora', ' d', ' Carrefour Market ou Magasins U', ' France ou Miribel', ' https://fr.openfoodfacts.org/produit/3250546100055/amora-moutarde-fine-et-forte-verre-de-table-245g'),
	(76, 'Pizza 4 Saisons', 'pizza_7', 'pizza', ' Carte Nature', ' c', ' ', ' ', ' https://fr.openfoodfacts.org/produit/3700477606350/pizza-4-saisons-carte-nature'),
	(77, 'Tarte aux poireaux', 'quiche_7', 'quiche', ' Toque du Chef', ' d', ' LIDL', ' Etréchy', ' https://fr.openfoodfacts.org/produit/20291013/tarte-aux-poireaux-toque-du-chef'),
	(78, 'Basmati Rice', 'riz_7', 'riz', ' Naturaplan ou Coop ou  Coop naturaplan', ' a', ' Coop', ' Suisse', ' https://fr.openfoodfacts.org/produit/7611654532705/basmati-rice-naturaplan'),
	(79, 'Delikatess Lyoner', 'saucisse_7', 'saucisse', ' Edeka', ' e', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/4314187031952/delikatess-lyoner-edeka'),
	(80, 'Le Pur Boeuf \n10 Steaks hachés', 'steack_7', 'steack', ' Carrefour', ' b', ' Carrefour', ' ', ' https://fr.openfoodfacts.org/produit/3270190020103/le-pur-boeuf-10-steaks-haches-carrefour'),
	(81, 'Maslo Milfina', 'beurre_8', 'beurre', ' Milfina', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/4099200028019/maslo-milfina'),
	(82, 'Olio Extra vergine di oliva', 'huile_8', 'huile', ' Bertolli', ' c', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/8002470025370/olio-extra-vergine-di-oliva-bertolli'),
	(83, 'Tomato Ketchup', 'ketchup_8', 'ketchup', ' Heinz', ' d', ' Carrefour', ' France ou Muzillac', ' https://fr.openfoodfacts.org/produit/87157116/tomato-ketchup-heinz'),
	(84, 'Sauce Snack- Mayonnaise de Dijon', 'mayonnaise_8', 'mayonnaise', ' Amora ou Unilever Food Solutions', ' e', ' Noz', ' ', ' https://fr.openfoodfacts.org/produit/3250541919874/sauce-snack-mayonnaise-de-dijon-amora'),
	(85, 'Moutarde de dijon', 'moutarde_8', 'moutarde', ' Delouis', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3258831007447/moutarde-de-dijon-delouis'),
	(86, 'Pizza Chorizo', 'pizza_8', 'pizza', ' Thiriet', ' d', ' Thiriet', ' Aix les Bains', ' https://fr.openfoodfacts.org/produit/3292590824914/pizza-chorizo-thiriet'),
	(87, 'Tarte aux poireaux', 'quiche_8', 'quiche', ' Monique Ranou', ' c', ' Intermarché', ' Laragne ou France', ' https://fr.openfoodfacts.org/produit/3250390025399/tarte-aux-poireaux-monique-ranou'),
	(88, 'Basmati-reis', 'riz_8', 'riz', ' NOT_PROVIDED', ' b', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/5410673000095/basmati-reis'),
	(89, 'Plateau de saucisses VOLAILLE', 'saucisse_8', 'saucisse', ' Carrefour', ' d', ' Carrefour', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3560070847068/plateau-de-saucisses-volaille-carrefour'),
	(90, 'Haché pur boeuf', 'steack_8', 'steack', ' Dabia', ' NOT_PROVIDED', ' Carrefour', ' France', ' https://fr.openfoodfacts.org/produit/3039050047953/hache-pur-boeuf-dabia'),
	(91, 'NOT_PROVIDED', 'beurre_9', 'beurre', ' st hubert omega 3', ' NOT_PROVIDED', ' houra', ' France', ' https://fr.openfoodfacts.org/produit/3366321053277/st-hubert-omega-3'),
	(92, 'Huile d olive vierge extra', 'huile_9', 'huile', ' Cauvin', ' NOT_PROVIDED', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3336590080328/huile-d-olive-vierge-extra-cauvin'),
	(93, 'Ketchup sin gluten', 'ketchup_9', 'ketchup', ' Prima', ' d', ' El Corte Inglés ou  Hipercor ou  Condis ou  Carrefour ou  Eroski ou  Caprabo ou Dia', ' España', ' https://fr.openfoodfacts.org/produit/8410118042465/ketchup-prima'),
	(94, 'Amora Mayonnaise De Dijon Nature Flacon Souple 710g Lot de 4 + 2 Offerts', 'mayonnaise_9', 'mayonnaise', ' Amora', ' e', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/8712100235412/amora-mayonnaise-de-dijon-nature-flacon-souple-710g-lot-de-4-2-offerts'),
	(95, 'Maille Moutarde au Céleri et Brisures de Truffes 110g', 'moutarde_9', 'moutarde', ' Maille', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/8722700344292/maille-moutarde-au-celeri-et-brisures-de-truffes-110g'),
	(96, 'Ristorante Pizza Pepperoni-Salame', 'pizza_9', 'pizza', ' Dr.Oetker ou Ristorante', ' d', ' REWE ou Marktkauf', ' ', ' https://fr.openfoodfacts.org/produit/4001724820208/ristorante-pizza-pepperoni-salame-dr-oetker'),
	(97, 'Quiche Lorraine', 'quiche_9', 'quiche', ' By Sainsbury-s', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/01145267/quiche-lorraine-by-sainsbury-s'),
	(98, 'Thai Jasmin (riz long grain)', 'riz_9', 'riz', ' Vitasia', ' a', ' LIDL ou Lidl', ' Osnabrück ou Deutschland ou Hénin-Beaumont ou Etréchy ou Würzburg', ' https://fr.openfoodfacts.org/produit/20035259/thai-jasmin-vitasia'),
	(99, 'Chipolatas herbes', 'saucisse_9', 'saucisse', ' Bioporc', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3483190011655/chipolatas-herbes-bioporc'),
	(100, '1 Steak Haché pur Bœuf', 'steack_9', 'steack', ' Jean Rozé ou Intermarché', ' b', ' Intermarché', ' France', ' https://fr.openfoodfacts.org/produit/3250390311508/1-steak-hache-pur-boeuf-jean-roze'),
	(101, 'Le Campagnou Bio Beurre Moulé Demi-Sel', 'beurre_10', 'beurre', ' Loyez Woessen', ' e', ' Leader Price', ' France', ' https://fr.openfoodfacts.org/produit/3596589000021/le-campagnou-bio-beurre-moule-demi-sel-loyez-woessen'),
	(102, 'Huile d-olive', 'huile_10', 'huile', ' Cauvin', ' NOT_PROVIDED', ' Magasins U', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3336590083282/huile-d-olive-cauvin'),
	(103, 'Ketchup', 'ketchup_10', 'ketchup', ' Jardin Bio', ' e', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3478822935249/ketchup-jardin-bio'),
	(104, 'Amora Mayonnaise Dijon Nature Œufs Français Flacon Souple Flacon Souple 685g 4 + 2 Offerts', 'mayonnaise_10', 'mayonnaise', ' Amora', ' e', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/8712423053052/amora-mayonnaise-dijon-nature-oeufs-francais-flacon-souple-flacon-souple-685g-4-2-offerts'),
	(105, 'Löwensenf medium pikant', 'moutarde_10', 'moutarde', ' ', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/42094685/lowensenf-medium-pikant'),
	(106, 'Die Backfrische Lachs Spinat', 'pizza_10', 'pizza', ' Wagner', ' NOT_PROVIDED', ' ', ' ', ' https://fr.openfoodfacts.org/produit/7613036427203/lachs-spinat-wagner'),
	(107, 'Mushroom & spinah quiche', 'quiche_10', 'quiche', ' Marks & Spencer', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/00862271/mushroom-spinah-quiche-marks-spencer'),
	(108, 'Natur-Reis Basmati', 'riz_10', 'riz', ' Uncle Ben’s', ' NOT_PROVIDED', ' ', ' ', ' https://fr.openfoodfacts.org/produit/5010034007499/natur-reis-basmati-uncle-ben-s'),
	(109, 'Cervelas', 'saucisse_10', 'saucisse', ' Tradilège ou Marque Repère', ' e', ' Leclerc', ' France', ' https://fr.openfoodfacts.org/produit/3661112055110/cervelas-tradilege'),
	(110, 'Steaks Hachés Bio', 'steack_10', 'steack', ' Carrefour', ' NOT_PROVIDED', ' Carrefour', ' France', ' https://fr.openfoodfacts.org/produit/3245415313155/steaks-haches-bio-carrefour'),
	(111, 'Beurre frigotartinable', 'beurre_11', 'beurre', ' Carlsbourg', ' d', ' Delhaize', ' Belgique', ' https://fr.openfoodfacts.org/produit/5411156003541/beurre-frigotartinable-carlsbourg'),
	(112, 'Huile de pepins de courge Cauvin', 'huile_11', 'huile', ' Cauvin', ' NOT_PROVIDED', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3336590101283/huile-de-pepins-de-courge-cauvin'),
	(113, 'Ketchup Heinz', 'ketchup_11', 'ketchup', ' Heinz', ' d', ' Magasins U ou  Delhaize', ' ', ' https://fr.openfoodfacts.org/produit/87157277/ketchup-heinz'),
	(114, 'Mayonnaise', 'mayonnaise_11', 'mayonnaise', ' Calvé', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/8711200559718/mayonnaise-calve'),
	(115, 'Moutarde de Dijon', 'moutarde_11', 'moutarde', ' Bioster ou Bister', ' d', ' Biocoop', ' ', ' https://fr.openfoodfacts.org/produit/3760128280650/moutarde-de-dijon-bioster'),
	(116, 'Pizza Crousty Cheese 3 fromages', 'pizza_11', 'pizza', ' Carrefour', ' d', ' Carrefour', ' ', ' https://fr.openfoodfacts.org/produit/3560070602407/pizza-crousty-cheese-3-fromages-carrefour'),
	(117, 'Quiche lorraine Stalaven', 'quiche_11', 'quiche', ' Jean Stalaven', ' d', ' ', ' France', ' https://fr.openfoodfacts.org/produit/3181580262204/quiche-lorraine-stalaven-jean-stalaven'),
	(118, 'Riz Thaï Blanc', 'riz_11', 'riz', ' Markal', ' NOT_PROVIDED', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3329485531203/riz-thai-blanc-markal'),
	(119, 'Schinken-Fleischwurst', 'saucisse_11', 'saucisse', ' viel Leicht', ' c', ' ', ' ', ' https://fr.openfoodfacts.org/produit/4314240074537/schinken-fleischwurst-viel-leicht'),
	(120, '2 Steaks hachés 15% MG pur bœuf Bio', 'steack_11', 'steack', ' Charal', ' c', ' Leclerc', ' Tignieu ou France', ' https://fr.openfoodfacts.org/produit/3181232220163/2-steaks-haches-15-mg-pur-boeuf-bio-charal'),
	(121, 'Beurre De Baratte Doux', 'beurre_12', 'beurre', ' Bordier', ' e', ' ', ' ', ' https://fr.openfoodfacts.org/produit/3760191050006/beurre-de-baratte-doux-bordier'),
	(122, 'Huile d-olive', 'huile_12', 'huile', ' Cauvin', ' NOT_PROVIDED', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3336590065011/huile-d-olive-cauvin'),
	(123, 'Amora Tomato Ketchup Nature Flacon Top Up 575g Lot de 8+4 Offerts', 'ketchup_12', 'ketchup', ' Amora', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/8712100935220/amora-tomato-ketchup-nature-flacon-top-up-575g-lot-de-8-4-offerts'),
	(124, 'Calve- Maionese', 'mayonnaise_12', 'mayonnaise', ' Calvé', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/8722700263623/calve-maionese'),
	(125, 'Moutarde Douce', 'moutarde_12', 'moutarde', ' Carrefour', ' d', ' Carrefour', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3560070940219/moutarde-douce-carrefour'),
	(126, 'Pizza margherita', 'pizza_12', 'pizza', ' Alice & Bio', ' c', ' ', ' ', ' https://fr.openfoodfacts.org/produit/3760209680973/pizza-margherita-alice-bio'),
	(127, 'Tarte aux poireaux pâte pur beurre', 'quiche_12', 'quiche', ' Casino', ' d', ' Casino', ' Paris ou France ou Maison-Laffitte', ' https://fr.openfoodfacts.org/produit/3222475507458/tarte-aux-poireaux-pate-pur-beurre-casino'),
	(128, 'Riz basmati', 'riz_12', 'riz', ' Saint Eloi', ' a', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/99003333/riz-basmati-saint-eloi'),
	(129, 'Schinken Zwiebel Mettwurst', 'saucisse_12', 'saucisse', ' Westfalen Krone', ' NOT_PROVIDED', ' ', ' ', ' https://fr.openfoodfacts.org/produit/4043362657365/schinken-zwiebel-mettwurst-westfalen-krone'),
	(130, 'Steak haché pur boeuf', 'steack_12', 'steack', ' Carrefour', ' a', ' Carrefour', ' Chatenay Malabry ou Rennes', ' https://fr.openfoodfacts.org/produit/3245414151017/steak-hache-pur-boeuf-carrefour'),
	(131, 'Beurre', 'beurre_13', 'beurre', ' Prima', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/7610900025268/beurre-prima'),
	(132, 'Huile d-Olive vierge extra', 'huile_13', 'huile', ' Cauvin', ' NOT_PROVIDED', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3336599883784/huile-d-olive-vierge-extra-cauvin'),
	(133, 'Ketchup fine ligne allégé', 'ketchup_13', 'ketchup', ' leader price', ' c', ' Leader Price', ' ', ' https://fr.openfoodfacts.org/produit/3263850684210/ketchup-fine-ligne-allege-leader-price'),
	(134, 'Mayonnaise', 'mayonnaise_13', 'mayonnaise', ' Calvé', ' e', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/8714100905999/mayonnaise-calve'),
	(135, 'Moutarde Douce', 'moutarde_13', 'moutarde', ' Carrefour', ' d', ' Carrefour', ' Lyon ou France', ' https://fr.openfoodfacts.org/produit/3560070940189/moutarde-douce-carrefour'),
	(136, 'Pizza Surgelée (quattro Formaggi)', 'pizza_13', 'pizza', ' Dr Oetker', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/0058336170065/pizza-surgelee-quattro-formaggi-dr-oetker'),
	(137, 'Quiche Poireaux Emmental', 'quiche_13', 'quiche', ' Monoprix', ' d', ' Monoprix', ' Saint-Etienne 42', ' https://fr.openfoodfacts.org/produit/3350033676206/quiche-poireaux-emmental-monoprix'),
	(138, 'Riz long basmati', 'riz_13', 'riz', ' U', ' a', ' Super U ou  Magasins U', ' Marseille 5°', ' https://fr.openfoodfacts.org/produit/3256221212426/riz-long-basmati-u'),
	(139, 'Nürnberger Rostbratwurst', 'saucisse_13', 'saucisse', ' HoWe', ' NOT_PROVIDED', ' ', ' ', ' https://fr.openfoodfacts.org/produit/4002960405549/nurnberger-rostbratwurst-howe'),
	(140, 'Steaks hachés pur boeuf 5% MG', 'steack_13', 'steack', ' Carrefour', ' b', ' Carrefour', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3245415330381/steaks-haches-pur-boeuf-5-mg-carrefour'),
	(141, 'pro activ expert', 'beurre_14', 'beurre', ' fruit d-or', ' NOT_PROVIDED', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/0209811018376/pro-activ-expert-fruit-d-or'),
	(142, 'Huile olive vierge extra', 'huile_14', 'huile', ' Cauvin', ' c', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3336590096503/huile-olive-vierge-extra-cauvin'),
	(143, 'Ketchup light', 'ketchup_14', 'ketchup', ' Dia', ' b', ' Dia', ' Fouquières-les-Lens ou France', ' https://fr.openfoodfacts.org/produit/8480017747716/ketchup-light-50-sucres-dia'),
	(144, 'Maille Mayonnaise Fine Qualité Traiteur Bocal 320g', 'mayonnaise_14', 'mayonnaise', ' Maille', ' e', ' Magasins U ou leclerc', ' France', ' https://fr.openfoodfacts.org/produit/8718114734484/maille-mayonnaise-fine-qualite-traiteur-bocal-320g'),
	(145, 'Löwensenf ou  Medium', 'moutarde_14', 'moutarde', ' Löwensenf', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/42094692/lowensenf-medium'),
	(146, 'Pizza bio- au sarrazin 4 saison sans gluten', 'pizza_14', 'pizza', ' Jardin Bio', ' c', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3760018888720/pizza-bio-au-sarrazin-4-saison-sans-gluten-jardin-bio'),
	(147, 'Quiche lorraine surgelée', 'quiche_14', 'quiche', ' Toupargel', ' c', ' ', ' ', ' https://fr.openfoodfacts.org/produit/3760011177227/quiche-lorraine-surgelee-toupargel'),
	(148, 'Riz thai long grain', 'riz_14', 'riz', ' Taureau ailé', ' b', ' Magasins U', ' ', ' https://fr.openfoodfacts.org/produit/3038359007095/riz-thai-long-grain-taureau-aile'),
	(149, 'Tradival Chipolatas précuites le paquet de 20 1', 'saucisse_14', 'saucisse', ' Tradival', ' e', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3608568290078/tradival-chipolatas-precuites-le-paquet-de-20-1'),
	(150, 'Steack hache', 'steack_14', 'steack', ' Charal', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/3181232520188/steack-hache-charal'),
	(151, 'Beurre Tendre Doux', 'beurre_15', 'beurre', ' Président', ' e', ' Leclerc ou Magasins U', ' France ou Nantes', ' https://fr.openfoodfacts.org/produit/3155251205524/beurre-tendre-doux-president'),
	(152, 'Huile d-olive vierge extra', 'huile_15', 'huile', ' Cauvin', ' NOT_PROVIDED', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3336599880714/huile-d-olive-vierge-extra-cauvin'),
	(153, 'Amora Ketchup Nature Flacon Souple 550g Offre Saisonnière', 'ketchup_15', 'ketchup', ' Amora', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/8712100774584/amora-ketchup-nature-flacon-souple-550g-offre-saisonniere'),
	(154, 'Amora Mayonnaise Dijon Nature Œufs Français Offre Saisonnière Flacon Souple 685g', 'mayonnaise_15', 'mayonnaise', ' amora', ' e', ' ', ' ', ' https://fr.openfoodfacts.org/produit/8714100867099/amora-mayonnaise-dijon-nature-oeufs-francais-offre-saisonniere-flacon-souple-685g'),
	(155, 'Moutarde de dijon forte', 'moutarde_15', 'moutarde', ' Bouton d-Or', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3250391416950/moutarde-de-dijon-forte-bouton-d-or'),
	(156, '4 fromages', 'pizza_15', 'pizza', ' Fiorini', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/3250392571870/4-fromages-fiorini'),
	(157, 'Quiche Lorraine', 'quiche_15', 'quiche', ' Marie', ' d', ' Intermarché ou Irma.dk ou Magasins U', ' Cannes', ' https://fr.openfoodfacts.org/produit/3248830085058/quiche-lorraine-marie'),
	(158, 'Riz Basmati long Max Havelaar', 'riz_15', 'riz', ' Casino', ' a', ' ', ' ', ' https://fr.openfoodfacts.org/produit/3222476875051/riz-basmati-long-max-havelaar-casino'),
	(159, 'Saucisse de Toulouse', 'saucisse_15', 'saucisse', ' Tradival', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3608568201432/saucisse-de-toulouse-tradival'),
	(160, 'Steak haché ou  5% MAT.GR.', 'steack_15', 'steack', ' U', ' a', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3256220182065/steak-hache-5-mat-gr-u'),
	(161, 'Burro', 'beurre_16', 'beurre', ' Fiandino', ' d', ' ', ' ', ' https://fr.openfoodfacts.org/produit/8001408870099/burro-fiandino'),
	(162, 'Huile vierge de chanvre', 'huile_16', 'huile', ' Cauvin', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3336590103294/huile-vierge-de-chanvre-cauvin'),
	(163, 'Amora Ketchup Plaisir+ Stevia Flacon Souple 465g', 'ketchup_16', 'ketchup', ' Amora', ' c', ' Leclerc ou Magasins U', ' Rennes ou France', ' https://fr.openfoodfacts.org/produit/8722700162667/amora-ketchup-plaisir-stevia-flacon-souple-465g'),
	(164, 'Amora Mayonnaise Dijon Nature Œufs Français Offre Saissoniere Flacon Souple 395g', 'mayonnaise_16', 'mayonnaise', ' Amora', ' e', ' ', ' ', ' https://fr.openfoodfacts.org/produit/8714100867037/amora-mayonnaise-dijon-nature-oeufs-francais-offre-saissoniere-flacon-souple-395g'),
	(165, 'Moutarde a l-ancienne', 'moutarde_16', 'moutarde', ' Bouton d-Or', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/15334638/moutarde-a-l-ancienne-bouton-d-or'),
	(166, 'pizza 3 fromages', 'pizza_16', 'pizza', ' E.Leclerc', ' c', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3478920006407/pizza-3-fromages-e-leclerc'),
	(167, 'Quiche Lorraine - surgelé', 'quiche_16', 'quiche', ' Monique Ranou ou Claude Léger ou Sélection Intermarché ou Les Mousquetaires', ' b', ' Intermarché', ' Cannes ou France', ' https://fr.openfoodfacts.org/produit/3250390884033/quiche-lorraine-surgele-monique-ranou'),
	(168, 'Basmati Reis Vollkorn', 'riz_16', 'riz', ' Alnatura ou Altanatura', ' a', ' Edeka ou  Alnatura', ' Münster', ' https://fr.openfoodfacts.org/produit/4104420018426/riz-complet-basmati-alnatura'),
	(169, 'Chipolatas', 'saucisse_16', 'saucisse', ' Tradival', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3608568201326/chipolatas-tradival'),
	(170, 'Steak haché ou  15% MAT.GR.', 'steack_16', 'steack', ' U', ' c', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3256220182072/steak-hache-15-mat-gr-u'),
	(171, 'Beurre demi-sel Bio', 'beurre_17', 'beurre', ' pâturages', ' e', ' ', ' ', ' https://fr.openfoodfacts.org/produit/3250392744793/beurre-demi-sel-bio-paturages'),
	(172, 'Huile d-olive vierge extra', 'huile_17', 'huile', ' Cauvin', ' NOT_PROVIDED', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3336590080052/huile-d-olive-vierge-extra-cauvin'),
	(173, 'Amora Ketchup Nature Top Up 826g', 'ketchup_17', 'ketchup', ' Amora', ' d', ' Carrefour Market ou Cora ou Magasins U', ' Normandie ou France ou Courrières', ' https://fr.openfoodfacts.org/produit/8718114780887/amora-ketchup-nature-top-up-826g'),
	(174, 'Amora Mayonnaise Dijon Nature Œufs Français Flacon Souple 395g', 'mayonnaise_17', 'mayonnaise', ' amora', ' e', ' ', ' ', ' https://fr.openfoodfacts.org/produit/8714100866962/amora-mayonnaise-dijon-nature-oeufs-francais-flacon-souple-395g'),
	(175, 'Sauce Salade &quot;La Miel Moutarde&quot;', 'moutarde_17', 'moutarde', ' Amora ou Unilever Food Solutions', ' d', ' Noz', ' ', ' https://fr.openfoodfacts.org/produit/8717163809570/sauce-salade-la-miel-moutarde-amora'),
	(176, 'Pizza kit', 'pizza_17', 'pizza', ' Wewalka', ' c', ' ', ' ', ' https://fr.openfoodfacts.org/produit/9001536015187/pizza-kit-wewalka'),
	(177, 'Quiche Lorraine', 'quiche_17', 'quiche', ' U', ' c', ' Magasins U', ' ', ' https://fr.openfoodfacts.org/produit/3256224160007/quiche-lorraine-u'),
	(178, 'Jasmin Reis', 'riz_17', 'riz', ' Bamboo Garden', ' NOT_PROVIDED', ' ', ' ', ' https://fr.openfoodfacts.org/produit/4058700541152/jasmin-reis-bamboo-garden'),
	(179, 'Merguez', 'saucisse_17', 'saucisse', ' Tradival', ' e', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3608568200251/merguez-tradival'),
	(180, 'Steak haché ou  12% MAT.GR.', 'steack_17', 'steack', ' U', ' NOT_PROVIDED', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3256220066846/steak-hache-12-mat-gr-u'),
	(181, 'Benecol à tartiner', 'beurre_18', 'beurre', ' Au beurre', ' d', ' Delhaize', ' ', ' https://fr.openfoodfacts.org/produit/5055940100179/benecol-a-tartiner-au-beurre'),
	(182, 'Huile d olive vierge extra', 'huile_18', 'huile', ' Cauvin', ' c', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3336599880745/huile-d-olive-vierge-extra-cauvin'),
	(183, 'Amora Ketchup Ingrédients d-Origine Naturelle Flacon Souple 469g', 'ketchup_18', 'ketchup', ' Amora ou Unilever', ' c', ' Leclerc ou  Magasins U', ' Niort ou France', ' https://fr.openfoodfacts.org/produit/8714100091883/amora-ketchup-ingredients-d-origine-naturelle-flacon-souple-469g'),
	(184, 'Amora Mayonnaise Dijon Nature Œufs Français Flacon Souple 685g', 'mayonnaise_18', 'mayonnaise', ' Amora', ' e', ' ', ' ', ' https://fr.openfoodfacts.org/produit/8714100866924/amora-mayonnaise-dijon-nature-oeufs-francais-flacon-souple-685g'),
	(185, 'Moutarde a l-ancienne aux graines et au vin blanc de Bourgogne', 'moutarde_18', 'moutarde', ' Edmond Fallot', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/80912491/moutarde-a-l-ancienne-aux-graines-et-au-vin-blanc-de-bourgogne-edmond-fallot'),
	(186, 'Kit à Pizza', 'pizza_18', 'pizza', ' Auchan', ' a', ' Auchan', ' ', ' https://fr.openfoodfacts.org/produit/3596710418374/kit-a-pizza-auchan'),
	(187, 'Quiche Lorraine la french ou  spécial micro-ondes', 'quiche_18', 'quiche', ' U', ' d', ' Super U ou  Magasins U', ' France ou Nantes ou Carquefou', ' https://fr.openfoodfacts.org/produit/3256226092672/quiche-lorraine-la-french-special-micro-ondes-u'),
	(188, 'Jasmine rice', 'riz_18', 'riz', ' Trader Joe-s', ' b', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/00522526/jasmine-rice-trader-joe-s'),
	(189, '6 Cumberland sausages', 'saucisse_18', 'saucisse', ' Marks & Spencer', ' NOT_PROVIDED', ' Marks & Spencer', ' France ou Paris', ' https://fr.openfoodfacts.org/produit/00481724/6-cumberland-sausages-marks-spencer'),
	(190, 'Steack haché maxi tendre ou  5% MAT.GR.', 'steack_18', 'steack', ' U', ' NOT_PROVIDED', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3256220851411/steack-hache-maxi-tendre-5-mat-gr-u'),
	(191, 'Matière grasse légère 15%', 'beurre_19', 'beurre', ' Les Croisés ou Marque Repère', ' e', ' E.Leclerc ou Leclerc', ' France', ' https://fr.openfoodfacts.org/produit/3564700500996/matiere-grasse-legere-15-les-croises'),
	(192, 'Huile vierge de tournesol oleique', 'huile_19', 'huile', ' Cauvin', ' d', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/3336590103720/huile-vierge-de-tournesol-oleique-cauvin'),
	(193, 'Amora Ketchup Nature Flacon Top Up - Offre Saisonnière 575 GR', 'ketchup_19', 'ketchup', ' Amora ou Unilever', ' d', ' ', ' France', ' https://fr.openfoodfacts.org/produit/8712566362509/amora-ketchup-nature-flacon-top-up-offre-saisonniere-575-gr'),
	(194, 'Amora Sauce Aïoli avec Huile d-Olive 182g', 'mayonnaise_19', 'mayonnaise', ' amora', ' d', ' Magasins U', ' ', ' https://fr.openfoodfacts.org/produit/8714100908105/amora-sauce-aioli-avec-huile-d-olive-182g'),
	(195, 'Moutarde de Dijon', 'moutarde_19', 'moutarde', ' Edmond Fallot', ' a', ' ', ' ', ' https://fr.openfoodfacts.org/produit/3230140002443/moutarde-de-dijon-edmond-fallot'),
	(196, 'Pizza Tradizionale Mozzarella e Pesto', 'pizza_19', 'pizza', ' Dr. Oetker', ' c', ' Willys ou ICA Supermarket ou Delhaize', ' Sweden', ' https://fr.openfoodfacts.org/produit/4001724019893/pizza-tradizionale-mozzarella-e-pesto-dr-oetker'),
	(197, 'Tarte aux poireaux', 'quiche_19', 'quiche', ' U', ' c', ' Super U ou  Magasins U', ' France ou Carquefou', ' https://fr.openfoodfacts.org/produit/3256224706021/tarte-aux-poireaux-u'),
	(198, 'Arroz basmati', 'riz_19', 'riz', ' Consum', ' b', ' NOT_PROVIDED', ' NOT_PROVIDED', ' https://fr.openfoodfacts.org/produit/8414807516336/arroz-basmati-consum'),
	(199, 'Haricots blancs et saucisse de Toulouse', 'saucisse_19', 'saucisse', ' Maison Rivière', ' a', ' ', ' ', ' https://fr.openfoodfacts.org/produit/3375644008208/haricots-blancs-et-saucisse-de-toulouse-maison-riviere'),
	(200, 'Steak hache bio pur boeuf 15% de MG SOVIBA', 'steack_19', 'steack', ' Sourires de Campagne', ' NOT_PROVIDED', ' Carrefour', ' France', ' https://fr.openfoodfacts.org/produit/3265980154564/steak-hache-bio-pur-boeuf-15-de-mg-soviba-sourires-de-campagne');
/*!40000 ALTER TABLE `aliment` ENABLE KEYS */;

-- Listage de la structure de la table db_purebeurre. category
CREATE TABLE IF NOT EXISTS `category` (
  `id` varchar(50) NOT NULL,
  `name` varchar(50) NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Listage des données de la table db_purebeurre.category : ~0 rows (environ)
/*!40000 ALTER TABLE `category` DISABLE KEYS */;
INSERT INTO `category` (`id`, `name`) VALUES
	('1', 'beurre'),
	('2', 'huile'),
	('3', 'ketchup'),
	('4', 'mayonnaise'),
	('5', 'moutarde'),
	('6', 'pizza'),
	('7', 'quiche'),
	('8', 'riz'),
	('9', 'saucisse'),
	('10', 'steack');
/*!40000 ALTER TABLE `category` ENABLE KEYS */;

-- Listage de la structure de la table db_purebeurre. historic
CREATE TABLE IF NOT EXISTS `historic` (
  `swap_id` int(10) NOT NULL AUTO_INCREMENT,
  `aliment_id` int(10) DEFAULT NULL,
  `substituted_id` int(10) DEFAULT NULL,
  PRIMARY KEY (`swap_id`),
  KEY `FK_aliment_id` (`aliment_id`),
  KEY `FK_substituted_id` (`substituted_id`),
  CONSTRAINT `FK_aliment_id` FOREIGN KEY (`aliment_id`) REFERENCES `aliment` (`id`),
  CONSTRAINT `FK_substituted_id` FOREIGN KEY (`substituted_id`) REFERENCES `aliment` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Listage des données de la table db_purebeurre.historic : ~0 rows (environ)
/*!40000 ALTER TABLE `historic` DISABLE KEYS */;
/*!40000 ALTER TABLE `historic` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
